services:
  mysql:
    image: mysql:8.0
    container_name: gen_analytics_mysql
    environment:
      MYSQL_ROOT_PASSWORD: genanalytics
      MYSQL_DATABASE: gen_analytics
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pgenanalytics"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
