"""Evaluation harness for the GenAnalytics agent.

Runs test cases from YAML files, captures the SQL generated by the agent,
and checks it against expected tables and patterns. Outputs a scorecard.

Usage:
    python scripts/evaluate.py                      # All test cases, dry-run
    python scripts/evaluate.py --category simple     # Only simple cases
    python scripts/evaluate.py --category medium     # Only medium cases
    python scripts/evaluate.py --category complex    # Only complex cases
    python scripts/evaluate.py -n 3                  # First 3 per category
    python scripts/evaluate.py --save                # Save results to JSONL
"""

import argparse
import asyncio
import json
import os
import re
import sys
import time
from datetime import datetime
from pathlib import Path

import yaml

# Add backend to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from google.genai import types
from google.adk import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import FunctionTool

from app.agent.agent import create_agent


EVAL_DIR = Path(__file__).parent.parent / "tests" / "eval"
RESULTS_DIR = EVAL_DIR / "results"


def _make_execute_sql_stub():
    """Stub execute_sql that doesn't scan data."""
    def execute_sql(sql: str, max_rows: int = 100) -> dict:
        """Stub: returns a message instead of running the query."""
        return {
            "columns": ["info"],
            "rows": [{"info": "[DRY-RUN] Query validated but not executed."}],
            "total_rows": 0,
            "bytes_processed": 0,
        }
    return execute_sql


def load_test_cases(category: str | None = None) -> list[dict]:
    """Load test cases from YAML files."""
    cases = []
    files = {
        "simple": EVAL_DIR / "simple_queries.yaml",
        "medium": EVAL_DIR / "medium_queries.yaml",
        "complex": EVAL_DIR / "complex_queries.yaml",
    }

    targets = {category: files[category]} if category else files
    for cat, path in targets.items():
        if path.exists():
            with open(path) as f:
                loaded = yaml.safe_load(f) or []
                for case in loaded:
                    case.setdefault("complexity", cat)
                cases.extend(loaded)
    return cases


def check_tables(sql: str, expected_tables: list[str]) -> tuple[bool, list[str]]:
    """Check if expected tables appear in the SQL."""
    missing = []
    for table in expected_tables:
        if table.lower() not in sql.lower():
            missing.append(table)
    return len(missing) == 0, missing


def check_patterns(sql: str, expected_patterns: list[str]) -> tuple[bool, list[str]]:
    """Check if expected patterns appear in the SQL.

    Patterns can use | for OR (e.g. 'JOIN|IN|EXISTS' means any of those).
    """
    missing = []
    for pattern in expected_patterns:
        if "|" in pattern:
            # OR pattern -- any alternative must match
            alternatives = pattern.split("|")
            if not any(alt.lower() in sql.lower() for alt in alternatives):
                missing.append(pattern)
        else:
            if pattern.lower() not in sql.lower():
                missing.append(pattern)
    return len(missing) == 0, missing


async def run_single_case(
    runner: Runner, user_id: str, case: dict, case_num: int
) -> dict:
    """Run a single test case and return the result."""
    question = case["question"]

    # Each test case gets its own session for isolation
    session_service = runner.session_service
    session = await session_service.create_session(
        app_name="gen_analytics", user_id=user_id
    )

    message = types.Content(
        role="user", parts=[types.Part(text=question)]
    )

    captured_sql = []
    validation_passed = False
    tool_sequence = []
    final_text = ""
    start_time = time.time()

    async for event in runner.run_async(
        user_id=user_id,
        session_id=session.id,
        new_message=message,
    ):
        if not event.content or not event.content.parts:
            continue
        for part in event.content.parts:
            if part.function_call:
                fc = part.function_call
                tool_sequence.append(fc.name)
                if fc.args and "sql" in fc.args:
                    captured_sql.append(fc.args["sql"])

            if part.function_response:
                fr = part.function_response
                resp = fr.response
                if isinstance(resp, dict) and resp.get("is_valid"):
                    validation_passed = True

            if part.text:
                final_text = part.text

    elapsed = time.time() - start_time

    # Use the last SQL submitted (after self-correction)
    sql = captured_sql[-1] if captured_sql else ""

    # Check expectations
    tables_ok, missing_tables = check_tables(sql, case.get("expected_tables", []))
    patterns_ok, missing_patterns = check_patterns(sql, case.get("expected_patterns", []))
    passed = tables_ok and patterns_ok and validation_passed

    # Status icon
    icon = "✅" if passed else "❌"
    print(f"  {icon} [{case_num}] {question[:70]}")
    if not passed:
        if not validation_passed:
            print(f"       ⚠ SQL validation failed")
        if missing_tables:
            print(f"       ⚠ Missing tables: {missing_tables}")
        if missing_patterns:
            print(f"       ⚠ Missing patterns: {missing_patterns}")

    return {
        "question": question,
        "complexity": case.get("complexity", "unknown"),
        "passed": passed,
        "validation_passed": validation_passed,
        "tables_ok": tables_ok,
        "patterns_ok": patterns_ok,
        "missing_tables": missing_tables,
        "missing_patterns": missing_patterns,
        "sql": sql,
        "tool_sequence": tool_sequence,
        "elapsed_seconds": round(elapsed, 1),
        "answer_preview": final_text[:150],
    }


async def main():
    parser = argparse.ArgumentParser(description="Evaluate the GenAnalytics agent")
    parser.add_argument(
        "--category", choices=["simple", "medium", "complex"],
        help="Run only one category",
    )
    parser.add_argument("-n", type=int, default=0, help="Max cases per category (0 = all)")
    parser.add_argument("--save", action="store_true", help="Save results to JSONL file")
    args = parser.parse_args()

    # Load test cases
    cases = load_test_cases(args.category)
    if args.n > 0:
        # Limit per category
        limited = []
        seen = {}
        for c in cases:
            cat = c.get("complexity", "unknown")
            seen.setdefault(cat, 0)
            if seen[cat] < args.n:
                limited.append(c)
                seen[cat] += 1
        cases = limited

    if not cases:
        print("No test cases found.")
        return

    # Create agent with execute_sql stubbed out
    agent = create_agent()
    stub = _make_execute_sql_stub()
    agent.tools = [
        t if t.func.__name__ != "execute_sql" else FunctionTool(stub)
        for t in agent.tools
    ]

    session_service = InMemorySessionService()
    runner = Runner(
        app_name="gen_analytics",
        agent=agent,
        session_service=session_service,
    )

    print(f"🧪 Evaluating {len(cases)} test cases (dry-run mode)\n")

    # Run all cases
    results = []
    for i, case in enumerate(cases, 1):
        result = await run_single_case(runner, "eval_user", case, i)
        results.append(result)

    # Scorecard
    print(f"\n{'='*60}")
    print("SCORECARD")
    print(f"{'='*60}")

    by_category = {}
    for r in results:
        cat = r["complexity"]
        by_category.setdefault(cat, []).append(r)

    total_passed = 0
    total_count = 0
    for cat in ["simple", "medium", "complex"]:
        if cat not in by_category:
            continue
        cat_results = by_category[cat]
        passed = sum(1 for r in cat_results if r["passed"])
        count = len(cat_results)
        total_passed += passed
        total_count += count
        pct = (passed / count * 100) if count else 0
        bar = "█" * int(pct / 5) + "░" * (20 - int(pct / 5))
        print(f"  {cat:8s}: {passed:2d}/{count:2d} ({pct:5.1f}%) {bar}")

    overall_pct = (total_passed / total_count * 100) if total_count else 0
    print(f"  {'OVERALL':8s}: {total_passed:2d}/{total_count:2d} ({overall_pct:5.1f}%)")

    # Failure analysis
    failures = [r for r in results if not r["passed"]]
    if failures:
        print(f"\n{'='*60}")
        print(f"FAILURE ANALYSIS ({len(failures)} failures)")
        print(f"{'='*60}")
        reasons = {"validation_failed": 0, "wrong_table": 0, "missing_pattern": 0}
        for r in failures:
            if not r["validation_passed"]:
                reasons["validation_failed"] += 1
            if not r["tables_ok"]:
                reasons["wrong_table"] += 1
            if not r["patterns_ok"]:
                reasons["missing_pattern"] += 1
        for reason, count in sorted(reasons.items(), key=lambda x: -x[1]):
            if count > 0:
                print(f"  {reason}: {count}")

    # Save results
    if args.save:
        RESULTS_DIR.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        out_path = RESULTS_DIR / f"eval_{timestamp}.jsonl"
        with open(out_path, "w") as f:
            for r in results:
                f.write(json.dumps(r) + "\n")
        print(f"\nResults saved to {out_path}")


if __name__ == "__main__":
    asyncio.run(main())
