"""GenAnalytics agent -- translates natural language to SQL and executes it."""

import json
import os

from google.adk.agents import LlmAgent
from google.adk.tools import FunctionTool

from app.agent.prompts import build_system_prompt
from app.agent.tools.execute_sql import execute_sql
from app.agent.tools.get_sample_data import get_sample_data
from app.agent.tools.validate_sql import validate_sql
from app.schema.formatter import format_terse_schema

# Path to cached schema metadata (generated by scripts/extract_schema.py)
_SCHEMA_CACHE = os.path.join(
    os.path.dirname(__file__), "..", "..", "data", "schema_metadata.json"
)


def _load_terse_schema() -> str:
    """Load terse schema from cached metadata JSON."""
    path = os.path.abspath(_SCHEMA_CACHE)
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Schema cache not found at {path}. "
            "Run: python scripts/extract_schema.py <datasets...>"
        )
    with open(path) as f:
        metadata = json.load(f)
    return format_terse_schema(metadata)


def create_agent() -> LlmAgent:
    """Create and return the GenAnalytics ADK agent."""
    terse_schema = _load_terse_schema()
    prompt = build_system_prompt(terse_schema)
    return LlmAgent(
        name="gen_analytics",
        model="gemini-2.5-flash",
        instruction=prompt,
        tools=[FunctionTool(validate_sql), FunctionTool(execute_sql), FunctionTool(get_sample_data)],
    )
